engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          python_version: 3
    checks:
      Similar code:
        enabled: false
    plugins:
      pep8:
        enabled: true
      sonar-python:
        enabled: true
